---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: jmcarp/pulledpork

inputs:
- name: snort-release-source

outputs:
- name: snort-pulledpork-source

run:
  path: snort-release-source/ci/tasks/pulledpork.sh
