---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: 18fgsa/concourse-task

inputs:
- name: snort-release-source

outputs:
- name: finalized-release

run:
  path: snort-release-source/ci/tasks/update-release.sh
