---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: 18fgsa/

inputs:
- name: snort-pulledpork-source

outputs:
- name: finalized-release

run:
  path: snort-pulledpork-source/ci/update-release.sh
